"use strict";
let myNumb = 10;
let myStr = 'Some string';
let myBool = true;
let myAny = 25;
myAny = 'any string';
let myNumb2 = 10;
let myStr2 = 'Some string';
let myBool2 = true;
let myAny2;
myAny2 = true;
myAny2 = 25;
let myNumb3 = 25;
myNumb3 = true;
